In [13]:
class fib(object):
    def __init__(self,max):
        self.max=max
        self.n,self.a,self.b=0,0,1
    def __iter__(self):
        return self
    def __next__(self):#有iter必需有next来决定如何迭代
        if self.n<self.max:
            r=self.b
            self.a,self.b=self.b,self.a+self.b
            self.n+=1
            return r
        raise StopIteration()#StopIteration指某些错误情况，本行表示遇到错误情况停止
for i in fib(5):
    print(i)


1
1
2
3
5


In [1]:
def fib(ob):
    a,b=0,1
    while ob:
        r=b
        a,b=b,a+b
        yield r#保留当前状态并立即返回结果给调用者,用于迭代
        ob-=1
fib(5)
for i in fib(5):
    print(i)

1
1
2
3
5


In [5]:
dict={'x':0,'y':1,'z':2}
for i in dict:#i会迭代字典的的key而非key值
    if dict[i]>1:
        print('z')
    elif dict[i]<1:
        print('x')
    else:
        print('y')
print('finish')

y
x
z
finish


In [23]:
def sale_club(price,color='red',brand='rng',is_second_hand=True):
    print('price', price,
         'color',color,
         'brand',brand,
         'is_second_hand',is_second_hand)
sale_club(1,brand='ig')


price 1 color red brand ig is_second_hand True


In [1]:
def report(name,*grades,**kw):
    total_grade=0
    for grade in grades:
        total_grade+=grade
    print(name,'total grade is',total_grade)
    for k,v in kw.items():
        print(k,v)

report('张三',1,2,2,sex='male')

张三 total grade is 5
sex male


In [30]:
Apple=100
a=None
def fun():
    global a#引用外部变量
    a=20
    return a+100
print('\ta past','\n\t%s'%a)#\n换行，\t对其，%s占位
print('\t%s'%Apple)
fun()
print('\ta now','\n\t%s'%a)

	a past 
	None
	100
	a now 
	20


In [32]:
text='this is my first text. \nthis is the second line. \nthis is the third'
print(text)
myfile=open('泊松回归模型.txt','w')
myfile.write(text)
myfile.close()

this is my first text. 
this is the second line. 
this is the third


In [1]:
append_text='this is an append line'#'w'会覆盖源文件，'a'为添加
f=open('myfile.txt','a')
f.write(append_text)
f.close()

In [6]:

f=open('myfile.txt','r')#readline会默认读取下一行下一行，如前边为read在readline为空
c1=f.readline()
c2=f.readline()
f.close()#关闭文档解除占用
c2

'this is the second line. \n'

In [7]:
f=open('myfile.txt','r')#按行全部读取
c=f.readlines()
f.close
for i in c:
    print(i)

this is my first text. 

this is the second line. 

this is the third

this is an append line


In [10]:
class Calculator:
    name='Good Calculator'
    price=18
    def __init__(self,name=name,price=price,length=0,width=0,height=0):#给出了默认值，不给出默认值引用时需要全部赋值
        self.name=name
        self.price=price
        self.length=length
        self.width=width
        self.height=height
    def add(self,x,y):
        print(self.name)
        print(self.price)
        print(x+y)
    def minus(self,x,y):
        print(x-y)
    def times(self,x,y):
        print(x*y)
    def divide(self,x,y):
        print(x/y)
cal=Calculator(name='Hello Calculator',length=1)

cal.add(1,2)

Hello Calculator
19
3


In [20]:
score=int(input('please input your score:\n'))#input 输入默认为str
if score>=90:
    print('A')
elif score>=80:
    print('B')
elif score>=70:
    print('C')
elif score>=60:
    print('D')
else:
    print('you are failed')


please input your score:
77
C


In [27]:
a_tuple=(1,2,3)
tuple=1,2,3
a_list=[1,2,3]
for i in a_tuple:
    print(i)
for i in a_list:
    print(i)
for index in range(len(tuple)):
    print('index=',index,'number in a tuple=',tuple[index])#tuple和list索引都用[]
for index in range(len(a_list)):
    print('index=',index,'number in a list=',a_list[index])

1
2
3
1
2
3
index= 0 number in a tuple= 1
index= 1 number in a tuple= 2
index= 2 number in a tuple= 3
index= 0 number in a list= 1
index= 1 number in a list= 2
index= 2 number in a list= 3


In [15]:
#list的增删、排序、索引、计数、+
a=[1,3,5,13,9,7,2,1]
a.append(4)
b=a
a.remove(3)
c=a
a.sort()
d=a
a.sort(reverse=True)
e=a
print('b',b,'c',c,
'index',a.index(4),
'count',a.count(1),'d',d,'e',e
)
multi_dim_a=[[1,3,5],[13,9,7],[7,2,1]]
print('multi_dim',multi_dim_a[0][2],'+',
      a+[2,2])


b [13, 9, 7, 5, 4, 2, 1, 1] c [13, 9, 7, 5, 4, 2, 1, 1] index 4 count 2 d [13, 9, 7, 5, 4, 2, 1, 1] e [13, 9, 7, 5, 4, 2, 1, 1]
multi_dim 5 + [13, 9, 7, 5, 4, 2, 1, 1, 2, 2]


In [20]:
#字典的key对应的值可以为int、str、列表、函数等
d1={1:'a','b':2,'c':'c'}
del d1[1]
d1['2']='n'
d1['list1']=[1,2,3,'a']
def func(a):
    return a**2
d1['pf']=func(2)
d1['list1'][3]#对字典中的列表进行引用

'a'

In [ ]:
#True、False判断后跳出循环、break直接跳出循环、continue直接进行下一个循环
a=True
while a:
    b=input('please input something')
    if b=='1':
        break#  a=False  continue
    else:
        pass
    print('still in a while')
print('finish run')

please input something2
still in a while
please input something3
still in a while
please input something1
please input something1
please input something1
please input something1


In [8]:
#try和except可用于捕获异常
try:
    b=(input('please input a name of txt'))
    f=open(b,'r')
    f.read()
    f.close()
except Exception as e:#将错误类型语句存储于e
    print(e)
    a=input('do you want to creat a new file y/n')
    if a=='y':
        f=open(b,'w')
        f.write(input('please write a line'))
        f.close()
    else:
        pass
else:
    pass


please input a name of txtaaaaaa.txt
[Errno 2] No such file or directory: 'aaaaaa.txt'
do you want to creat a new file y/ny
please write a linehello hhhh


In [3]:
a=[1,2,3,10,11,13]
b=[4,5,6]
ab=zip(a,b)#zip将a,b的参数分别合并，转化为tuple进行存储
type(ab)#输出为zip型
#只会返回可合并项,两函数返回结果一样
def func1(x):
    for i,j in list(x):
        print(i,j)
def func2(x):
    for i,j in x:
        print(i,j)



1 4
2 5
3 6


In [7]:
#lambda可以简化函数定义
func=lambda x,y:x+y
print(func(1,2))
#map将函数和参数绑在一起输入
list(map(func,[1,2,3],[4,5,6]))#需要用list将map结果打印出来

3


[5, 7, 9]

In [42]:
#浅拷贝与深拷贝以及列表、字典的复制
#mutable list dict等
#imutable （部分 number、str） 、tuple等
import copy
a=[1,2,[1,2,3]]
print(id(a))#id为a在内存中的地址

b=copy.copy(a)#浅拷贝只拷贝一个对象，内部元素只拷贝引用
print(id(b))#拷贝后对象保存的地址不同
b[0]=2
print(a,b)#由于整数（整数在python中会分配一定的缓存地址）为immutable所以b将自己的引用改变，而a未变

b[2][1]=3
print('改变新建地址元素后',a,b)#这次改变没有改变引用，而是修改了地址内的元素，a，b都改变

#如果a的对象和内部元素都为immutable，则copy和deepcopy都不存在copy
#但是immutable的对象中若存在mutable则可以改变，原理同mutable对象
a=(1,2,3)
b=copy.copy(a)
print(c)
print(id(a)==id(b))#id相同
#无法更改内部元素，所以不存在拷贝
try:
    b[2]=1
except Exception as e:
    print(e)

#深拷贝不仅会拷贝对象，还会对内部元素进行拷贝，但是immutable元素依然会指向系统默认引用，只会对mutable新建存储地址
a=[1,2,[1,2,3]]
b=copy.deepcopy(a)
print(id(a)==id(b))#false

#改变immutable或者mutable另一个都不会改变
b[0]=2
b[2][1]=3
print('deepcopy 改变后',a,b)

#list、dict的赋值运算与copy不同,相当于对同一个对象贴不同的标签，改变盒子的东西a，b都变
#以dict为例
a={1:'a',2:'world'}
b=a
b[1]=2
print('赋值运算',a,b)

#四种集合（list\tuple\dict\set）的其他复制操作copy() 函数、分片操作[:]、dict（）、list（）与浅拷贝相似
#如list\dict\set.copy(),b=dict\list\set\tuple(a),list\tuple=a[:]

2416244654664
2416244655624
[1, 2, [1, 2, 3]] [2, 2, [1, 2, 3]]
改变新建地址元素后 [1, 2, [1, 3, 3]] [2, 2, [1, 3, 3]]
(1, 2, 3)
True
'tuple' object does not support item assignment
False
deepcopy 改变后 [1, 2, [1, 2, 3]] [2, 2, [1, 3, 3]]
赋值运算 {1: 2, 2: 'world'} {1: 2, 2: 'world'}


In [7]:
#python的压缩工具pickle
import pickle
a=[1,2,3]
f=open('pickle_example.pickle','wb')#wb以二进制方式写入
pickle.dump(a,f)#将a写入f
f.close()
with open('pickle_example.pickle','rb') as f:#with open（） as 系统会自动完成f.close（） 
    b=pickle.load(f)#利用pickle模块读取f
print(b)

[1, 2, 3]


In [1]:
#set（）集合可自动去重
a=[1,1,2,2,3,3,4,4]
b='welcome to PeiKing'
print(set(a+list(b)))
a=set(a)
a.add('a')
print(a)
try:
    a.add([1,2])#无法添加list
except Exception as e:
    print(e)
a.remove(2)
print(a)
a.discard(1)
print(a)
print(a.difference([1,2,3,4]))#difference寻找出a有但b没有那部分
print(a.intersection([1,2,3,4]))#取交集
print(a.clear())#清空set

{'m', 1, 2, 3, 4, 'l', 'c', 't', 'n', ' ', 'K', 'e', 'g', 'i', 'P', 'w', 'o'}
{'a', 1, 2, 3, 4}
unhashable type: 'list'
{'a', 1, 3, 4}
{'a', 3, 4}
{'a'}
{3, 4}
None


In [13]:
#正则表达式简介
import re
p1='cat'
p2='bird'
string='dog runs to cat. cats ran to dogs'
print(re.search(p1,string))
print(re.search(p2,string))
#[]匹配中括号内部包括匹配的内容
#在正则前加r表示为正则表达式
#0-9 a-z A-Z 匹配0-9内任意数字 a-z A-Z同
p3='r[0-9a-zA-z]n'
print('0-9 a-z A-Z任意数字字母',re.search(p3,string))
#\d： any decimal digit
print('\d 任意十进制数字',re.search(r'r\dn','run r9n'))
#\D:  any non-decimal digit
print('\D 非十进制数字',re.search(r'r\Dn','run r9n'))
# \s : any white space [\t\n\r\f\v]
print('\s 任意空白字符',re.search(r'r\sn','run r\nn'))
# \S : any non-white space opposite to \s
print('\S 匹配非空白字符',re.search(r'r\Sn','run r\nn'))
#\w:[0-9a-zA-Z]
print('\w包括下划线在内的任何字字符',re.search(r'r\wn','run r\nn'))
#\W:opposite to \w
print('\W 任何非字字符',re.search(r'r\Wn','run r\nn'))
#\b: 单词与符号之间的边界，如'a,'\b就是'a'与','的边界
print(r" \b 单词与符号之间的边界，如'a,'\b就是'a'与','的边界",re.search(r'\brun\b',',run, '))
#\B: 
print('\B 单词与单词，符号与符号之间的边界',re.search(r'\Brun,\B','dogsrun, to cat'))
#\\:match \
print("'\\ 匹配 \'",re.search(r'run\\','dogs run\ to cat'))
# .:match anything(without /n)
print(r'. 匹配任何除了\n',re.search('r.n','r\tn r\nn'))
# ^ :match beginning of line
print(r'^ 匹配行开头',re.search(r'^dog','cats run to cat \ndogs run to cat ',flags=re.M))
# $ :match end of line
print('$ 匹配行结尾',re.search('cat$','dogs run to cat'))#如果在cat后有空格则最后一位为符号结果为none
# ? : may or may not occur
print('？ 0次或这1次',re.search('mon(day)?','monday'))
print('？ 0次或这1次',re.search('mon(day)?','mon'))
#search 默认只处理一行，定义参数flags=re.M 或flags=re.MULTILINE可进行多行处理
print('research 的参数flags=re.M可处理多行字符串结构',re.search(r'^dog','cats run to cat \ndogs run to cat ',flags=re.M))
string = '''
dog runs to cat.
I run to dog.
'''
print(re.search(r'^dog',string,flags=re.M))
# * : occur 0 to more
print('* 0次或多次',re.search('ab*','a'))
print('* 0次或多次',re.search('ab*','abbb'))
# + : occur 1 to more,
print('+ 1次或多次',re.search('ab+','a'))
print('+ 1次或多次',re.search('ab+','abbbb'))
# {n,m} : occur n to m
print('{n,m} n到m次',re.search('ab{2,10}','abbb'))
print('{n,} 至少n次',re.search('ab{2,10}','abbb'))
# {n} : occur n
print('{n} n次',re.search('ab{2}','abb'))

# () : 对匹配的内容分组
print('\n() 对匹配的内容分组')
m=re.search('(\d+), Date:(.+)','ID: 021523, Date: Feb/12/2017')#中间的 "， Date: "需与原句一致
print(m.group())#返回所有匹配的字符，默认为m.group(0)
print(m.group(1))#返回第一个括号匹配的字符
print(m.group(2))#返回第而个括号匹配的字符
# ?P<索引> : 为匹配到的组定义索引名
print('\n?P<index> 为匹配的组规则定义索引')
m=re.search('(?P<Id>\d+).+(?P<date>.+)','ID: 021523, Date: Feb/12/2017')
print(m.group('Id'))
print(m.group('date'))
# findall() : search()只会返回第一个匹配 findall（）会返回所有匹配
print('re.findall() 返回所有're.findall('r[ua]n','run ran running'))
# | : 表示或
print('A|B A或B 与一般的python判断不同，中间不能出现空格字符',re.findall('run|ran','run ran running'))#run与|间不能加空格
# split（）与python自带类似
print(re.split('[,:\.;]','1,2.3;4:5'))#\.用于区分功能 .
#compile（）保存正则规则
print('re.compile 保存正则匹配规则')
compiled_r=re.compile(r'run|ran')
print(compiled_r.findall('run ran running'))

<_sre.SRE_Match object; span=(12, 15), match='cat'>
None
0-9 a-z A-Z任意数字字母 <_sre.SRE_Match object; span=(4, 7), match='run'>
\d 任意十进制数字 <_sre.SRE_Match object; span=(4, 7), match='r9n'>
\D 非十进制数字 <_sre.SRE_Match object; span=(0, 3), match='run'>
\s 任意空白字符 <_sre.SRE_Match object; span=(4, 7), match='r\nn'>
\S 匹配非空白字符 <_sre.SRE_Match object; span=(0, 3), match='run'>
\w包括下划线在内的任何字字符 <_sre.SRE_Match object; span=(0, 3), match='run'>
\W 任何非字字符 <_sre.SRE_Match object; span=(4, 7), match='r\nn'>
 \b 单词与符号之间的边界，如'a,'\b就是'a'与','的边界 <_sre.SRE_Match object; span=(1, 4), match='run'>
\B 单词与单词，符号与符号之间的边界 <_sre.SRE_Match object; span=(4, 8), match='run,'>
'\ 匹配 ' <_sre.SRE_Match object; span=(5, 9), match='run\\'>
. 匹配任何除了\n <_sre.SRE_Match object; span=(0, 3), match='r\tn'>
^ 匹配行开头 <_sre.SRE_Match object; span=(17, 20), match='dog'>
$ 匹配行结尾 <_sre.SRE_Match object; span=(12, 15), match='cat'>
？ 0次或这1次 <_sre.SRE_Match object; span=(0, 6), match='monday'>
？ 0次或这1次 <_sre.SRE_Match object; span=(0, 3),

In [1]:
#multiprocessing threading
#多进程将进程放入多个cpu运行，多线程将进程分成若干小线程运行
import multiprocessing as mp
import threading as td
def job(a,b):
    print(a+b)
if __name__=='__main__':#没有的话会报错
    p1=mp.Process(target=job,args=(1,2))#参数放入args中,
    t1=td.Thread(target=job,args=(3,4))
#实现多进程，多线程实现同
    p1.start()
    p1.join()

In [ ]:
#由于多线程与多进程调用的函数不能有返回值，这时用queue将结果存入队列用便于调用
import multiprocessing as mp
def job(q):
    res=0
    for i in range(1000):
        res+=1
        q.put(res)#记录每一个res
if __name__=='__main__':
    q=mp.Queue()
    p=mp.Process(target=job,args=(q,))#参数只有一个值时，要保留逗号，表明可迭代

    p.start()
    p.join()
    res1=q.get()
    res2=q.get()
    print(res1,res2)#结果：1，2




In [ ]:
#比较不同运算方式的时间
import multiprocessing as mp
import threading as td
import time
#定义job函数
def job(q):
    res=0
    for i in range(int(1e+008)):
        res+=1
    q.put(res)#只将最后一个结果记录到q中
#定义多进程函数
def multicore():
    q=mp.Queue()
    p1=mp.Process(target=job,args=(q,))
    p2= mp.Process(target=job, args=(q,))
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    res1=q.get()
    res2=q.get()
    print('multicore',res1+res2)
#定义多线程函数
def multithread():
    q=mp.Queue()
    p1=td.Thread(target=job,args=(q,))
    p2= td.Thread(target=job, args=(q,))
    p1.start()
    p2.start()
    p1.join()
    p2.join()
    res1=q.get()
    res2=q.get()
    print('multithread',res1+res2)
#定义一个正常运算的函数，与多进程多线程的函数一样运算两遍
def normal():
    res=0
    for _ in range(2):
        for i in range(int(1e+008)):
            res+=1
    print('normal',res)
if __name__=='__main__':#只在内部引用，不用于外部
    std1=time.time()
    normal()
    std2=time.time()
    print('normal',std2-std1)
    multicore()
    std3=time.time()
    print('multicore',std3-std2)
    multithread()
    print('multithread',time.time()-std3)
#运行结果normal 200000000
#normal 10.115883350372314
#multicore 200000000
#multicore 5.866272211074829
#multithread 200000000
#multithread 9.9115469455719
#多进程最快为5.8秒

In [ ]:
#利用pool()实现多进程与Process不同，pool会返回中间值
import multiprocessing as mp
def job(x):
    return x*x
def multicore():
    pool=mp.Pool()
    res=pool.map(job,range(10))#map（）返回迭代值
    print(res)
    res=pool.apply_async(job,(2,))#pool 的 apply_async（）会返回单次值
    print(res.get())#apply_async（）返回值需要get()
#用apply_async()返回多个结果
#res = pool.apply_async(job, (2,3,4,))会报错，不支持迭代
# 代入迭代器
def multicore1():
    pool = mp.Pool()
    multi_res=[pool.apply_async(job,(i,)) for i in range(10)]
    print([res.get() for res in multi_res])
if __name__=='__main__':
    multicore()
    multicore1()

In [1]:
#multiprocessing使内存数据共享的shared value 与 shared array
#进程与进程之间是由边界的而共享内存可以打破这种边界
import multiprocessing as mp
#共享数据时需与定义数据类型，这些形式为c中对于类型的要求。python较少只有int float str等几类
value=mp.Value('d',3.14)#有符号双精浮点类型
value2=mp.Value('i',1)#有符号整型
#array只能为一维数据
array=mp.Array('i',[1,2,3,4])

In [22]:
#共享内存会出现多个进程争夺共享变量的情况，进程锁可以保证进程对于变量的独占
import multiprocessing as mp
import time
def job(v,num,l):#在赋值时加入锁变量
    l.acquire()#要求占用
    for i in range(10):
        time.sleep(0.1)#暂停0.1在试验时使争夺的现象更明显
        v.value+=num
        print(v.value,end=' ')#end=改变输出结尾的符号，默认为\n,这里改为‘ ’ 空格
    l.release()#占用释放
def multicore():
    l=mp.Lock()
    v=mp.Value('i',0)
    p1=mp.Process(target=job,args=(v,1,l))
    p2 = mp.Process(target=job, args=(v, 3,l))
    p1.start()
    p2.start()
    p1.join()
    p2.join()
if __name__=='__main__':
    multicore()

0
1
2
3
4
5
6
7
8
9


In [6]:
import threading as td
td.active_count()#获取已激活线程数
td.enumerate()#查看所有线程信息
td.current_thread()#查看正在运行的线程
def job():
    print('this is a thread of %s'%td.current_thread())
#定义一个多线程任务
def main():
    t=td.Thread(target=job)
    t.start()
if __name__=='__main__':
    main()

this is a thread of <Thread(Thread-6, started 8728)>


In [72]:
#join()的作用是确定主线程与某一线程的关系，jion()使该线程与jion（）后的主线程相连接
import threading as td
import time
def job1():
    print('T1 start\n')
    time.sleep(1)
    print('T1 finish\n')
    
def job2():
    print('T2 start\n')
    print('T2 finish\n')
t1=td.Thread(target=job1,name='T1')
t2=td.Thread(target=job2,name='T2')
t1.start()
t1.join()#jion（）与之后的线程连接，所以后边的执行要在t1完成后
t2.start()#t2未与后边连接，所以t2与后边的并行
print('all done\n')

T1 start

T1 finish

T2 start
all done


T2 finish



In [3]:
#多线程没有返回值，用Queue来保存
#这里的Queue直接引用queue类中的函数
import threading as td
from queue import Queue
def job(l,q):
    for i in range(len(l)):
        l[i]=l[i]**2
    q.put(l)
def multithread():
    q=Queue()
    threads=[]
    data=[[1,3,5],[2,4,5],[7,7,7],[1,1,1]]
    for i in range(4):
        t=td.Thread(target=job,args=(data[i],q))
        t.start()
        threads.append(t)
    for t in threads:
        t.join()
    results=[]
    for r in range(4):
        results.append(q.get())
    print(results)
if __name__=='__main__':
    multithread()
        

[[1, 9, 25], [4, 16, 25], [49, 49, 49], [1, 1, 1]]


In [ ]:
#Global Interpreter Lock简称GIL，指python的解释器c语言部分只能保证python的单个线程运行
#所以多线程程序只能在一个cpu中运行，无法利用多核
#多线程与普通函数对比
import threading as td
from queue import Queue
import time
import copy
def job(l,q):
    res=sum(l)
    q.put(res)
def multithread(l):
    q=Queue()
    threads=[]
    for i in range(4):
        t=td.Thread(target=job,args=(l,q))
        t.start()
        threads.append(t)
    [t.join() for t in threads]
    res=0
    for i in range(4):
        res+=q.get()
    print(res)
def normal(l):
    print(sum(l))
if __name__=='__main__':
    l=list(range(100000000))
    st=time.time()
    normal(l*4)
    print(time.time()-st)
    st=time.time()
    multithread(l)
    print(time.time()-st)

In [1]:
#threading 也有自己的线程锁Lock()
import time
import threading as td
def job1():
    global A,L
    L.acquire()
    for i in range(10):
        A+=1
        print('\tjob1 %s'%A)
    L.release()
def job2():
    global A,L
    L.acquire()
    for i in range(10):
        A+=10
        print('\tjob2 %s'%A)
    L.release()

if __name__=='__main__':
    L=td.Lock()
    A=0
    t1=td.Thread(target=job1)
    t2=td.Thread(target=job2)
    t1.start()
    t1.join()
    t2.start()
    t2.join()
  

	job1 1
	job1 2
	job1 3
	job2 200.021074533462524414	job1 4


	job2 30	job1 5

	job2 40	job1 6

	job2 50	job1 7

	job2 60	job1 8

	job2 70	job1 9

	job2 80	job1 10

	job2 90
	job2 100
	job2 110


In [ ]:
#利用 tkinter 包创建窗口
import tkinter as tk
w=tk.Tk()#创建窗口w
w.title('my window')
w.geometry('300x300')#设计窗口大小
var=tk.StringVar()#用于储存窗口的文本文档
#为w设置标签窗口
i=tk.Label(w,textvariable=var,bg='green',width=20,height=2,font='SimHei,12')#textvariable也可以直接自定义text=‘’的常量
i.pack()#label位置
on_hit=False
#定义hit后的函数
#这里每点击一次，on_hit 改变执行不同的变量，var就会改变
def hit():
    global on_hit
    if on_hit==False:
        on_hit=True
        var.set('please hit')
    else:
        on_hit=False
        var.set('IG NB')
#为w,定义按钮窗口
b=tk.Button(w,text='you hit me',width=10,height=1,font='Arial,10',command=hit)#操作函数为之前定义的hit（）
b.pack()#固定button窗口
w.mainloop()

In [2]:
#在tkinter中创建输入，输出按钮  
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')
#创建输入框Entry用户输入任何内容显示为*
e=tk.Entry(w,show='*')
e.pack()
#创建文本框用于显示
t=tk.Text(w,height=2)
t.pack()
#两个函数实际上实现的是近乎同样的功能
def insert_point():
    var=e.get()#var为entry中的内容
    t.insert('insert',var)#输入为‘insert’，表示在光标处插入
def insert_end():
    var=e.get()
    t.insert('end',var)#表示在最后插入
b1=tk.Button(w,text='insert point',width=15,height=2,command=insert_point)
b1.pack()
b2=tk.Button(w,text='insert end',width=15,height=2,command=insert_end)
b2.pack()
w.mainloop()


In [2]:
#在tkinter中应用listbox（列表部件）
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')
#创建文本存储变量
var1=tk.StringVar()
var2=tk.StringVar()
var2.set((1,2,3,4))#对var2赋值
#创建listbox，变量选择var2
lb=tk.Listbox(w,listvariable=var2)
#定义按钮的command函数，选取listbox中的变量作为对var1赋值
def print_selection():
    value=lb.get(lb.curselection())#curselection（）当下选择的值
    var1.set(value)
#对listbox做的值添加或修改
items=[11,22,33,44] 
for item in items:
    lb.insert('end',item)#listbox insert若干值
lb.insert('1','first')#listbox中position 1 插入值‘first’
lb.insert('2','second')
lb.delete('2')#删除listbox中位置2的值

#创建窗口的标签页
label_one=tk.Label(w,textvariable=var1,width=5,bg='yellow')#文本变量为var1
label_one.pack()
#创建按钮执行print_selection函数
button_one=tk.Button(w,text='print selection',width=10,height=2,command=print_selection)
button_one.pack()
lb.pack()

w.mainloop()

In [7]:
#tkinter 中的radiobutton （译为单项选择组件）组件
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')
l=tk.Label(w,text='entry',width=20,height=1,bg='yellow')
l.pack()
var=tk.StringVar()
#创建指令函数，对label ‘l’中的text进行修改
def print_selection():
    l.config(text='your option is '+ var.get())#config函数可以修改label中的参数
#创建三个radiobutton组件，每个都执行print_selection指令
#函数中的variable 与 value组合起来可看作对变量var赋value的值的操作
r1=tk.Radiobutton(w,text='option A',variable=var,value='A',command=print_selection)
r2=tk.Radiobutton(w,text='option B',variable=var,value='B',command=print_selection)
r3=tk.Radiobutton(w,text='option C',variable=var,value='C',command=print_selection)
r1.pack()
r2.pack()
r3.pack()

w.mainloop()

In [14]:
#tkinter中的scale(尺度)组件
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')
#创建label用于显示
l=tk.Label(w,text='empty',width=20,height=2,bg='yellow')
l.pack()
def print_selection(v):
    l.config(text='you have selected '+v)
s=tk.Scale(w,orient=tk.HORIZONTAL,label='try me',from_=5,to=11,resolution=0.01,length=200,showvalue=1,tickinterval=2,command=print_selection)
s.pack()
#from_与python中的from区分
#HORIZONTAL是在直接存在于tk中的变量，所以引用应该前缀tk.
#resolution保留几位小数
#length以像素尺度为标准
#showvalue是否显示值1为是
#tickinterval标记之间的距离为2
#orient尺度的方向
#label为尺度的label
#scale的command会自动给函数赋游标所处的值value
w.mainloop()

In [5]:
#应用tkinter中的Checkbutton
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')
#创建标签
l=tk.Label(w,bg='yellow',width=30,height=2,text='empty')
l.pack()
#IntVar用于存储int变量
var1=tk.IntVar()
var2=tk.IntVar()
def print_selection():
    v1=var1.get()
    v2=var2.get()
    if v1==1:
        if v2==1:
            l.config(text='I like both python and c++')
        else:
            l.config(text='I like python')
    elif v1==0:
        if v2==1:
            l.config(text='I like c++')
        else:
            l.config(text='I do not like anything')
#checkbutton与ratiobutton类似，不同之处在于onvalue与offvalue，即选与不选变量都会给变量赋值
chb1=tk.Checkbutton(w,width=10,height=3,text='python',variable=var1,onvalue=1,offvalue=0,command=print_selection)#选赋值1，不选赋值0
chb2=tk.Checkbutton(w,text='c++',variable=var2,onvalue=1,offvalue=0,command=print_selection)
chb1.pack()
chb2.pack()
w.mainloop()

In [41]:
#tkinter中的canvas(画布)
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')
#创建画布
canvas=tk.Canvas(bg='blue',width=260,height=160)
canvas.pack()
#向tkinter中导入图片
image_file=tk.PhotoImage(file=r'D:\下载\ins.gif')
#将图片导入到canvas中
image=canvas.create_image(10,10,anchor='nw',image=image_file)#以nw边角未锚点
#以下没有anchor，坐标以window为基点
#在画布中创建line(线)，oval(椭圆)，arc（弧），rectangle（矩形）
line=canvas.create_line(55,55,110,110)#四个点未x0,y0,x1,y1
oval=canvas.create_oval(55,55,110,110,fill='red')#fill以红色填充
arc=canvas.create_arc(110,110,180,180,start=0,extent=180)#起始为0度终止于180度
rect=canvas.create_rectangle(170,100,240,50,fill='green')
def moveit():
    canvas.move(rect,-1,-3)#移动画布上的图形rect，x,y移动-1，-3
b=tk.Button(width=15,height=1,text='move',command=moveit)
b.pack()
w.mainloop()

In [3]:
#tkinter的menu（菜单）
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')
l=tk.Label(width=10,height=1,bg='yellow',text='')
l.pack()
counter=0
#do_job,在label中显示counter，counter+=1
def do_job():
    global counter
    l.config(text='do '+str(counter))
    counter+=1
#定义quit函数，用于关闭窗口
def quit():
    w.quit()
    w.destroy()
#在w中创建初始菜单栏
menubar=tk.Menu(w)
w.config(menu=menubar)#置换w的菜单栏未menubar
#在mebubar中再设置新的菜单
filemenu=tk.Menu(menubar,tearoff=0)#tearoff表示是否可设置为悬浮菜单parameter未boolean
menubar.add_cascade(label='file',menu=filemenu)#将filemenu以悬瀑菜单的方式嵌入到menubar上，名为file
filemenu.add_command(label='New',command=do_job)#在filemenu上添加功能按键New
filemenu.add_command(label='Open',command=do_job)
filemenu.add_command(label='Save',command=do_job)
submenu=tk.Menu(filemenu,tearoff=0)#在filemenu中设置新的menu
filemenu.add_separator()#在filemenu下拉菜单栏加一条分割线
filemenu.add_cascade(label='Import',menu=submenu)#将submenu悬瀑式的嵌入filemenu
submenu.add_command(label='Quit',command=quit,underline=0)#在submenu上添加功能quit用于关闭窗口
#在menubar上添加新的菜单editmenu
editmenu=tk.Menu(menubar,tearoff=0)
menubar.add_cascade(label='Edit',menu=editmenu)
editmenu.add_command(label='Copy',command=do_job)
w.mainloop()

In [8]:
#利用Frame（框架）可以将tkinter分为不同的区域，便于管理
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')

tk.Label(w,bg='red',width=15,height=1,text='on the window').pack()

frm=tk.Frame(w)
frm.pack(side='bottom')#窗口中frame  pack的参数side的位置是绝对的

frm_l=tk.Frame(frm)
frm_r=tk.Frame(frm)
frm_l.pack(side='left')#frame内部pack()side的设定是相对的，如果只有一个pack，label居中
frm_r.pack(side='right')

tk.Label(frm_l,bg='yellow',width=10,height=1,text='on the left').pack()
tk.Label(frm_r,bg='green',width=10,height=1,text='on the right').pack()
tk.Label(frm,bg='blue',width=15,height=1,text='on the frame').pack()

w.mainloop()

In [1]:
#tkinter的messagebox(弹出对话框)
import tkinter as tk
from tkinter import messagebox#messagebox需要特殊的重新引入
w=tk.Tk()
w.title('my window')
w.geometry('300x300')

def hit_me():
    #tk.messagebox.showinfo(title='Hi',message='hahah') 提示信息对话框
    #tk.messagebox.showwarning(title='Hi',message='No!!') 提出警告对话框
    #tk.messagebox.showerror(title='Hi', message='Never!') 提示错误对话框
    tk.messagebox.askquestion(title='Hi',message='yes or no')#return True | Flase
tk.Button(w,text='hit me',command=hit_me).pack()
w.mainloop()

In [13]:
#tkinter中放置部件的三种方法pack\grid\place， 前两者无法共存，place可以与前两者分别共存
import tkinter as tk
w=tk.Tk()
w.title('my window')
w.geometry('300x300')

#函数pack()将部件放到上下左右
#tk.Label(w,text='top').pack(side='top')
#tk.Label(w,text='bottom').pack(side='bottom')
tk.Label(w,text='left').pack(side='left')
#tk.Label(w,text='right').pack(side='right')

#grid（）将部件以网格的形式放置
#for i in range(3):
    #for j in range(4):
       # tk.Label(w,text='%s'%i).grid(row=i,column=j,padx=10,pady=10)
#place以精确坐标来放置
tk.Label(w,text='place').place(x=10,y=20,anchor='nw')

w.mainloop()

In [3]:
#用tkinter搭建登陆窗口
import tkinter as tk
import pickle
from tkinter import messagebox
w=tk.Tk()
w.title('my window')
w.geometry('500x500')
#定义登陆函数
def login():
    user_name=var1.get()
    user_password=var2.get()
    #向打开用于存储用户信息的pickle文件，没有则创建一个
    try:
        with open('user_accounts.pickle','rb') as user_file:
            user_info=pickle.load(user_file)#读取pickle文档中的文件
    except FileNotFoundError:#如果发生没有发现文档的错误
        with open('user_accounts.pickle','wb') as user_file:
            user_info={'admin':'admin'}
            pickle.dump(user_info,user_file)#将user_info压缩进pickle.dump
    #比对输入的账号和密码是否正确
    if user_name in user_info:
        if user_password==user_info[user_name]:
            tk.messagebox.showinfo(title='welcome',message='How are you '+user_name)#信息栏窗口
        else:
            tk.messagebox.showerror(message='Error, your password is wrong. Try agin!')#错误栏窗口
    else:
        choice=tk.messagebox.askyesno(message='You have not sigh up yet. Sign up today?')#对choice赋值Ture | Flase
        if choice:
            sign_up()#选择注册账号则启动sign_up函数
def sign_up():
    #定义sign up window窗口中定义if_sign_up函数，用于比对账号是否可以注册
    def if_sign_up():
        #打开用户信息文档
        with open('user_accounts.pickle','rb') as user_file:
            user_info=pickle.load(user_file)
        u_n=s_var1.get()
        psw=s_var2.get()
        psw_cf=s_var3.get()
        #比对账号是否已存在，密码是否一致
        if u_n in user_info:
            tk.messagebox.showerror(title='Error',message='The user has already signed up!')
        elif psw!=psw_cf:
            tk.messagebox.showerror(title='Error',message='Password and confirm password must be the same!')
        else:
            user_info[u_n]=psw
            with open('user_accounts.pickle','wb') as user_file:
                pickle.dump(user_info,user_file)
            tk.messagebox.showinfo('Welcome','You have already successfully signed up. ')
            w_sign_up.destroy()#完成注册后摧毁窗口
        
    w_sign_up=tk.Toplevel(w)#新建用于注册的窗口
    w_sign_up.title('sign up window')
    w_sign_up.geometry('350x300')
    
    #创建可输入用户名和密码的Label和Entry
    s_var1=tk.StringVar()
    s_var1.set('Example@python.com')
    tk.Label(w_sign_up,text='User_name').place(x=30,y=50)
    tk.Entry(w_sign_up,textvariable=s_var1).place(x=150,y=50)
    
    s_var2=tk.StringVar()
    tk.Label(w_sign_up,text='Password').place(x=30,y=80)
    tk.Entry(w_sign_up,textvariable=s_var2,show='*').place(x=150,y=80)
    
    s_var3=tk.StringVar()
    tk.Label(w_sign_up,text='Confirm password').place(x=30,y=110)
    tk.Entry(w_sign_up,textvariable=s_var3,show='*').place(x=150,y=110)
    #创建注册按钮用于检验账号是否可以注册
    tk.Button(w_sign_up,text='Sign Up',command=if_sign_up).place(x=100,y=200)
#插入画布，画布中插入welcome图片
image_file=tk.PhotoImage(file='welcome.gif')
canvas=tk.Canvas(w,width=500,height=400)
canvas.create_image(35,35,anchor='nw',image=image_file)
canvas.pack(side='top')
#创建用于输入用户名和密码的窗口
tk.Label(w,text='User name').place(x=50,y=250)
tk.Label(w,text='Password').place(x=57,y=280)
var1=tk.StringVar()
var1.set('Example@python.com')
tk.Entry(w,textvariable=var1).place(x=150,y=250)
var2=tk.StringVar()
tk.Entry(w,textvariable=var2,show='*').place(x=150,y=280)
#创建登陆和注册按钮
tk.Button(w,text='Login',command=login).place(x=100,y=350)
tk.Button(w,text='Sign up',command=sign_up).place(x=200,y=350)
w.mainloop()

In [4]:
#Numpy基础
import numpy as np
a=np.array([[1,2,3],[2,3,4]])#将列表转化为矩阵

print('numpy.ndim',a.ndim)#查看矩阵的维度
print('numpy.size',a.size)#查看矩阵的元素个数
print('numpy.shape',a.shape)#查看矩阵的行列数

numpy.ndim 2
numpy.size 6
numpy.shape (2, 3)


array,int型(为int32) int32
array,int64型 int64
array,float型(为float64) float64
array,float32型 float32
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
空矩阵第一行 [  9.15916561e-312   9.15916561e-312   9.15916561e-312]
[[1]
 [4]
 [7]]
[  1.           1.47368421   1.94736842   2.42105263   2.89473684
   3.36842105   3.84210526   4.31578947   4.78947368   5.26315789
   5.73684211   6.21052632   6.68421053   7.15789474   7.63157895
   8.10526316   8.57894737   9.05263158   9.52631579  10.        ]
